version: '3'

services:
  jenkins:
    container_name: jenkins
    build: ./jenkins
    ports:
      - '8091:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
  
  webapp:
    container_name: webapp
    build: ./webapp
    ports:
      - "80:80"
  
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    # networks:
    #   - jenkins
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    restart: on-failure

volumes:
    jenkins_data:
        driver: local
    sonarqube_data:
        name: sonarqube_data
    sonarqube_extensions:
        name: sonarqube_extensions
    sonarqube_logs:
        name: sonarqube_logs